#!/bin/bash

# This script is for IT use meant to be ran from Self-Service or a like admin MDM portal. It will prompt the engineer for the new ID be created 
# and will set a temp password of P@ssw0rd until first login where SSO will enforce account sync with AD. 
#
#
#
#
#




currentUser=$(who | awk '/console/{print $1}')
echo $currentUser

user_entry=""

validateResponce() {
    case "$user_entry" in
        "noinput" ) echo "empty input" & askInput ;;
        "cancelled" ) echo "time out/cancelled" & exit 1 ;;
        * ) echo "$user_entry"  ;;
    esac
}

askInput() {
user_entry=$(osascript <<EOF
use AppleScript version "2.4" -- Yosemite (10.10) or later
use scripting additions
set theTextReturned to "nil"
tell application "System Events"
activate
try
set theResponse to display dialog "Please enter the partners NT Lan ID" with title "Create new Mac user account" default answer ""
set theTextReturned to the text returned of theResponse
end try
if theTextReturned is "nil" then
return "cancelled"
else if theTextReturned is "" then
return "noinput"
else
return theTextReturned
end if
end tell
EOF
)
validateResponce "$user_entry"
}

askInput
echo "$user_entry"
#Create the user account
sysadminctl -addUser "$user_entry" -fullName "$user_entry"  -password "P@ssw0rd" -hint "" -admin
